---
name: Release
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/run-docker-build.yaml@main
  python-release:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/push-python-release.yaml@main
    needs: docker-build
    permissions:
      contents: write
      issues: write
      pull-requests: write
  docker-release:
    uses: thibaultserti/gh-actions-reusable-workflows/.github/workflows/push-docker-release.yaml@main
    needs: python-release
    permissions:
      id-token: write # This is required for requesting the JWT
      packages: write
    with:
      release: ${{ needs.python-release.outputs.new_release_version}}
      use-prebuilt-image: true
      enable-signing: true
      platforms: "linux/amd64,linux/arm64/v8"
